/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as PlanoRouteImport } from './routes/plano'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as BeneficiosRouteImport } from './routes/beneficios'
import { Route as AdminClubeRouteImport } from './routes/admin-clube'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMinhasReservasRouteImport } from './routes/_authenticated/minhas-reservas'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const ReservasRoute = ReservasRouteImport.update({ id: '/reservas', path: '/reservas', getParentRoute: () => rootRouteImport } as any)
const ReservarRoute = ReservarRouteImport.update({ id: '/reservar', path: '/reservar', getParentRoute: () => rootRouteImport } as any)
const PlanoRoute = PlanoRouteImport.update({ id: '/plano', path: '/plano', getParentRoute: () => rootRouteImport } as any)
const PerfilRoute = PerfilRouteImport.update({ id: '/perfil', path: '/perfil', getParentRoute: () => rootRouteImport } as any)
const HistoricoRoute = HistoricoRouteImport.update({ id: '/historico', path: '/historico', getParentRoute: () => rootRouteImport } as any)
const DashboardRoute = DashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => rootRouteImport } as any)
const CheckinRoute = CheckinRouteImport.update({ id: '/checkin', path: '/checkin', getParentRoute: () => rootRouteImport } as any)
const BeneficiosRoute = BeneficiosRouteImport.update({ id: '/beneficios', path: '/beneficios', getParentRoute: () => rootRouteImport } as any)
const AdminClubeRoute = AdminClubeRouteImport.update({ id: '/admin-clube', path: '/admin-clube', getParentRoute: () => rootRouteImport } as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMinhasReservasRoute =
  AuthenticatedMinhasReservasRouteImport.update({
    id: '/minhas-reservas',
    path: '/minhas-reservas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-clube': typeof AdminClubeRoute
  '/beneficios': typeof BeneficiosRoute
  '/checkin': typeof CheckinRoute
  '/dashboard': typeof DashboardRoute
  '/historico': typeof HistoricoRoute
  '/perfil': typeof PerfilRoute
  '/plano': typeof PlanoRoute
  '/reservar': typeof ReservarRoute
  '/reservas': typeof ReservasRoute
  '/auth': typeof AuthRoute
  '/eventos': typeof EventosRoute
  '/ranking': typeof RankingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/minhas-reservas': typeof AuthenticatedMinhasReservasRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-clube': typeof AdminClubeRoute
  '/beneficios': typeof BeneficiosRoute
  '/checkin': typeof CheckinRoute
  '/dashboard': typeof DashboardRoute
  '/historico': typeof HistoricoRoute
  '/perfil': typeof PerfilRoute
  '/plano': typeof PlanoRoute
  '/reservar': typeof ReservarRoute
  '/reservas': typeof ReservasRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/eventos': typeof EventosRoute
  '/ranking': typeof RankingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/minhas-reservas': typeof AuthenticatedMinhasReservasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-clube'
    | '/beneficios'
    | '/checkin'
    | '/dashboard'
    | '/historico'
    | '/perfil'
    | '/plano'
    | '/reservar'
    | '/reservas'
    | '/auth'
    | '/eventos'
    | '/ranking'
    | '/admin'
    | '/minhas-reservas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin-clube' | '/auth' | '/beneficios' | '/checkin' | '/dashboard' | '/eventos' | '/historico' | '/perfil' | '/plano' | '/ranking' | '/reservar' | '/reservas' | '/admin' | '/minhas-reservas'
  id:
    | '__root__'
    | '/'
    | '/admin-clube'
    | '/beneficios'
    | '/checkin'
    | '/dashboard'
    | '/historico'
    | '/perfil'
    | '/plano'
    | '/reservar'
    | '/reservas'
    | '/_authenticated'
    | '/auth'
    | '/eventos'
    | '/ranking'
    | '/_authenticated/admin'
    | '/_authenticated/minhas-reservas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminClubeRoute: typeof AdminClubeRoute
  BeneficiosRoute: typeof BeneficiosRoute
  CheckinRoute: typeof CheckinRoute
  DashboardRoute: typeof DashboardRoute
  HistoricoRoute: typeof HistoricoRoute
  PerfilRoute: typeof PerfilRoute
  PlanoRoute: typeof PlanoRoute
  ReservarRoute: typeof ReservarRoute
  ReservasRoute: typeof ReservasRoute
  AuthRoute: typeof AuthRoute
  EventosRoute: typeof EventosRoute
  RankingRoute: typeof RankingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin-clube': { id: '/admin-clube'; path: '/admin-clube'; fullPath: '/admin-clube'; preLoaderRoute: typeof AdminClubeRouteImport; parentRoute: typeof rootRouteImport }
    '/beneficios': { id: '/beneficios'; path: '/beneficios'; fullPath: '/beneficios'; preLoaderRoute: typeof BeneficiosRouteImport; parentRoute: typeof rootRouteImport }
    '/checkin': { id: '/checkin'; path: '/checkin'; fullPath: '/checkin'; preLoaderRoute: typeof CheckinRouteImport; parentRoute: typeof rootRouteImport }
    '/dashboard': { id: '/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof DashboardRouteImport; parentRoute: typeof rootRouteImport }
    '/historico': { id: '/historico'; path: '/historico'; fullPath: '/historico'; preLoaderRoute: typeof HistoricoRouteImport; parentRoute: typeof rootRouteImport }
    '/perfil': { id: '/perfil'; path: '/perfil'; fullPath: '/perfil'; preLoaderRoute: typeof PerfilRouteImport; parentRoute: typeof rootRouteImport }
    '/plano': { id: '/plano'; path: '/plano'; fullPath: '/plano'; preLoaderRoute: typeof PlanoRouteImport; parentRoute: typeof rootRouteImport }
    '/reservar': { id: '/reservar'; path: '/reservar'; fullPath: '/reservar'; preLoaderRoute: typeof ReservarRouteImport; parentRoute: typeof rootRouteImport }
    '/reservas': { id: '/reservas'; path: '/reservas'; fullPath: '/reservas'; preLoaderRoute: typeof ReservasRouteImport; parentRoute: typeof rootRouteImport }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/minhas-reservas': {
      id: '/_authenticated/minhas-reservas'
      path: '/minhas-reservas'
      fullPath: '/minhas-reservas'
      preLoaderRoute: typeof AuthenticatedMinhasReservasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMinhasReservasRoute: typeof AuthenticatedMinhasReservasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMinhasReservasRoute: AuthenticatedMinhasReservasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminClubeRoute: AdminClubeRoute,
  BeneficiosRoute: BeneficiosRoute,
  CheckinRoute: CheckinRoute,
  DashboardRoute: DashboardRoute,
  HistoricoRoute: HistoricoRoute,
  PerfilRoute: PerfilRoute,
  PlanoRoute: PlanoRoute,
  ReservarRoute: ReservarRoute,
  ReservasRoute: ReservasRoute,
  AuthRoute: AuthRoute,
  EventosRoute: EventosRoute,
  RankingRoute: RankingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
